--- 
HOST_URL: "something.atlassian.net"
USER_EMAIL: "email address for the Atlassian account you're using to create the token (user.name@company.com)"
API_TOKEN: "token ID generated at https://id.atlassian.com/manage/api-tokens"
INCLUDE_ATTACHMENTS: "include attachments? this will make the backup size bigger - true / false"
DOWNLOAD_LOCALLY: "true"
UPLOAD_TO_OSS:
    ACCESS_KEY_ID: 'bucket access key id'
    ACCESS_KEY_SECRET: 'bucket access key secret'
    OSS_BUCKET: 'Ali OSS bucket name'
    OSS_DIR: 'Ali OSS directory for upload (example Atlassian)'
    ENDPOINT: 'Ali OSS endpoints https://www.alibabacloud.com/help/en/oss/user-guide/regions-and-endpoints'
